prompt Importing table mig_direcciones_conf...
set feedback off
set define off
insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600095781', '860009578', 0, 19000, 0, null, 73, 1, 'CR 4 C 33 08 BRR CADIZ', 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'SEGUROS DEL ESTADO S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600095783', '860009578', 0, 19000, 0, null, 11, 1100, 'CR 11  90  20 TESORERIA SEGUROS ESTADO', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2186977', null, '3155226801', 'CONSTANZA.RAMIREZ@SEGUROSDELESTADO.COM', 'SEGUROS DEL ESTADO S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600035631', '860003563', 0, 19000, 0, null, 11, 1, 'CARRERA 100 NO. 25D-61', 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3125840059', null, 'ABB LTDA');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600035633', '860003563', 0, 19000, 0, null, 11, 1100, 'AK 45  108  27 CENTRO EMPRESARIAL', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '4178000', null, '3134183633', 'ANGELA.SOLINA@CO.ABB.COM', 'ABB LTDA');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600399881', '860039988', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3103666102', null, 'LIBERTY SEGUROS S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('0000000000011', '000000000001', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'DIRECTO - SEGUROS CONFIANZA');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A00091491', '860037707', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3124571723', null, 'AIG SEGUROS COLOMBIA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A00091493', '860037707', 0, 19000, 0, null, 11, 1100, 'CL 78  9  57 CL 78 9 57', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3138700', null, '3124571723', 'JOHANNA.SAENZ@AIG.COM', 'AIG SEGUROS COLOMBIA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600399883', '860039988', 0, 19000, 0, null, 11, 1100, 'CL 72  10  07 PI 8 BOGOTA COLOMBIA', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3103300', null, '3103666102', 'CO-NOTIFICACIONES@LIBERTYCOLOMBIA.COM', 'LIBERTY SEGUROS S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600261821', '860026182', 0, 19000, 0, null, 11, 1, 'CR 13 A 29 24', 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ALLIANZ SEGUROS S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600261823', '860026182', 0, 19000, 0, null, 11, 1100, 'CR 13 A  29  24 TO COLSEGUROS PQUE CTAL B ACT SERVILLA PI 11', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '5600600', null, '3184664944', 'CAROLINA.GARZON@COLSEGUROS.COM', 'ALLIANZ SEGUROS S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600345201', '860034520', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, ' 6278     ', '3124576088', 'fdiaz@chubb.com', 'CHUBB DE COLOMBIA COMPANIA DE SEGUROS S.A');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600345203', '860034520', 0, 19000, 0, null, 11, 1100, 'CR 7  71  52 TO B PI 10 BRR ROSA', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3266200', null, '3124571722', 'MCROJAS@CHUBB.COM', 'CHUBB DE COLOMBIA COMPANIA DE SEGUROS S.A');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600021801', '860002180', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3116176545', 'martha.cifuentes@segurosbolivar.com', 'SEGUROS COMERCIALES BOLIVAR S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600021803', '860002180', 0, 19000, 0, null, 11, 1100, 'AC 26  68 B  31 PI DOMES', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '7810509', null, '3116176545', 'LUZ.MIRANDA@SEGUROSBOLIVAR.COM', 'SEGUROS COMERCIALES BOLIVAR S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A00688073', '890903407', 0, 19000, 0, null, 68, 6800, 'CR 35 A  48  75', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '6477757', null, '3137920510', 'AMENDEZF@SURA.COM.CO', 'SEGUROS GENERALES SURAMERICANA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A00546081', '860002400', 0, 19000, 0, null, 86, 1, 'CR 8 8 06 BRR CENTRO', 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'LA PREVISORA S.A. COMPAÑIA DE SEGUROS');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A00546083', '860002400', 0, 19000, 0, null, 11, 1100, 'CL 57  9  07 CUARTO NIVEL', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '6701643', null, '3213574227', 'GUSTAVO.SUANCHA@PREVISORA.GOV.COM', 'LA PREVISORA S.A. COMPAÑIA DE SEGUROS');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8605246543', '860524654', 0, 19000, 0, null, 5, 4, 'CR 99  95  25', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '6464330', null, '3124484484', 'MARIMARTINEZ@SOLIDARIA.COM.CO', 'ASEGURADORA SOLIDARIA DE COLOMBIA, ENTIDAD COOPERATIVA');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600025343', '860002534', 0, 19000, 0, null, 11, 1100, 'CR 7  76  35 PI 8 B BOGOTA', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3190730', null, null, 'IRMA.TORO@QBE.COM.CO', 'QBE SEGUROS S.A');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A00498083', '860002505', 0, 19000, 0, null, 11, 1100, 'AK 19  104  37 LC 101 C BRR', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '4881000', null, '3204499455', 'JUAN.PUCHANA@CO.RSAGROUP.COM', 'ROYAL & SUN ALLIANCE SEGUROS (COLOMBIA)  S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A00688071', '890903407', 0, 19000, 0, null, 5, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'SEGUROS GENERALES SURAMERICANA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8605246541', '860524654', 0, 19000, 0, null, 15, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3124484484', null, 'ASEGURADORA SOLIDARIA DE COLOMBIA, ENTIDAD COOPERATIVA');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A00498081', '860002505', 0, 19000, 0, null, 11, 1, 'CRA 43A NRO 1 SUR 188 OF 1106.       av.  19 no. 104-37', 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3204499455', null, 'ROYAL & SUN ALLIANCE SEGUROS (COLOMBIA)  S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600025341', '860002534', 0, 19000, 0, null, 11, 1, 'CR 7 76 35 P 8', 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'QBE SEGUROS S.A');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8917000371', '891700037', 0, 19000, 0, null, 11, 1, 'CR 7  16 50 PISO 6', 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '6503400   ', '3118982714', null, 'MAPFRE SEGUROS GENERALES DE COLOMBIA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8917000373', '891700037', 0, 19000, 0, null, 11, 1100, 'CR 14  96  34 BOGOTA D C DISTRI', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '6503300', null, '3168317805', 'LMCAMAC@MAPFRE.COM.CO', 'MAPFRE SEGUROS GENERALES DE COLOMBIA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A00876441', '800240882', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3115211444', null, 'BBVA SEGUROS DE VIDA COLOMBIA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A00876443', '800240882', 0, 19000, 0, null, 11, 1100, 'CR 9  72  21 PI 6', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2101600', null, '3105777334', 'HQUINTERO@BBVAHORIZONTE.COM.CO', 'BBVA SEGUROS DE VIDA COLOMBIA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600091951', '860009195', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2110218   ', null, 'diegocardozo@segurosexpo.com', 'SEGUREXPO DE COLOMBIA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600091953', '860009195', 0, 19000, 0, null, 11, 1100, 'CL 72  6  44 PI 12 ROSALES', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3266969', null, null, 'JPLUQUE@COLOMSAT.NET.CO', 'SEGUREXPO DE COLOMBIA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A00045501', '860004875', 0, 19000, 0, null, 11, 1, 'CRA 7 NO. 72-13 PISO 8', 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3146806683', null, 'GENERALI COLOMBIA SEGUROS GENERALES S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A00045503', '860004875', 0, 19000, 0, null, 11, 1100, 'CR 7  72  13 PI 1 5 Y 7', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3468888', null, '3146806683', 'CLAUDIA_VALBUENA@GENERALI.COM.CO', 'GENERALI COLOMBIA SEGUROS GENERALES S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A03408211', '860002527', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'NACIONAL DE  SEGUROS S.A. COMPAÑIA DE SEGUROS GENERALES');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A03408213', '860002527', 0, 19000, 0, null, 11, 1100, 'KR 14 N # 89 - 48 OF 401', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '6303820', null, null, 'OCANAS@ECOSEGUROS.COM.CO', 'NACIONAL DE  SEGUROS S.A. COMPAÑIA DE SEGUROS GENERALES');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A00143651', '860031979', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3155329057', null, 'SEGUROS ALFA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A00143653', '860031979', 0, 19000, 0, null, 11, 1100, 'CR 13  26 A  47 PI 22', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3444720', null, '3155329057', 'MARCO.RIANO@SEGUROSALFA.COM.CO', 'SEGUROS ALFA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A02503923', '860002182', 0, 19000, 0, null, 11, 1100, 'KR 9 # 74 - 62 COMERCIAL 00', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3139200', null, null, 'MARTHA.ECHEVERRIA@GLOBALSEGUROSCOLOMBIA.COM', 'GLOBAL SEGUROS DE VIDA S. A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A02503921', '860002182', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3175376   ', null, null, 'GLOBAL SEGUROS DE VIDA S. A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A00405691', '860008645', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'LIBERTY SEGUROS DE VIDA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A00405693', '860008645', 0, 19000, 0, null, 66, 6600, 'CL 17  6  42 PI 8', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3103300', null, null, 'SANDRAX.RUIZ@LIBERTYCOLOMBIA.COM', 'LIBERTY SEGUROS DE VIDA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A01224881', '860002945', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'CAPITALIZADORA COLPATRIA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A01224883', '860002945', 0, 19000, 0, null, 11, 1100, 'KR 7 # 24 - 89 PI 7 CENTRO INTERNAL', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3364677', null, null, 'COLPATRIA@EMPRESARIO.COM.CO', 'CAPITALIZADORA COLPATRIA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A02517131', '444444212', 0, 19000, 0, null, null, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'GENSER POWER INC');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8001498161', '800149816', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'AON BENFIELD COLOMBIA LTDA');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8001498163', '800149816', 0, 19000, 0, null, 11, 1100, 'CR 9  113  52 OF 505', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '6222222', null, null, 'ALEXANDER.HENAO@AONBENFIELD.COM', 'AON BENFIELD COLOMBIA LTDA');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8903004651', '890300465', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3134182706', 'judyrjuela@condorsas.com.co', 'CONDOR S.A. COMPAÑIA DE SEGUROS GENERALES - EN LIQUIDACION FORZOSA');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8903004653', '890300465', 0, 19000, 0, null, 11, 1100, 'CR 7  74  21 PI 1 TESORERIA', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3192930', null, '3134182706', 'KIKECAICER@GMAIL.COM', 'CONDOR S.A. COMPAÑIA DE SEGUROS GENERALES - EN LIQUIDACION FORZOSA');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('011', '860070374', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '6108388', null, null, '01. CENTRO ANDINO');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('013', '860070374', 0, 19000, 0, null, 11, 1100, 'CL 82 # 11 - 37 PI 7 EDIFICIO CONFIANZA BARRIO', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '6444690', null, null, 'AMOSCOSO@CONFIANZA.COM.CO', '01. CENTRO ANDINO');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600068201', '860006820', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ASEGURADORA GRANCOLOMBIANA S.A. (EN LIQUIDACION)');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600068203', '860006820', 0, 19000, 0, null, 11, 1100, 'CL 31  6  41', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '5561600', null, null, null, 'ASEGURADORA GRANCOLOMBIANA S.A. (EN LIQUIDACION)');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600054121', '860005412', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ASEGURADORA EL LIBERTADOR S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600054123', '860005412', 0, 19000, 0, null, 11, 1100, 'CR 13  26  45 PI 9', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2828100', null, null, null, 'ASEGURADORA EL LIBERTADOR S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A02988191', '444444490', 0, 19000, 0, null, null, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'RWD TECHNOLOGIES LLC');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600025191', '860002519', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'CIA. COLOMBIANA DE SEGUROS S.A. COLSEGUROS.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600025193', '860002519', 0, 19000, 0, null, 11, 1100, 'KR 13 A # 29 - 24 PI 13', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '5600601', null, null, 'VERONICA.VELASQUEZ@ALLIANZ.CO', 'CIA. COLOMBIANA DE SEGUROS S.A. COLSEGUROS.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8001470381', '800147038', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'GUY CARPENTER REINMEX LTDA');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8001470383', '800147038', 0, 19000, 0, null, 11, 1100, 'AC 26  69B  45 PI 9 SALITRE', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3769500', null, null, 'GCCOLOMBIA@GUYCARP.COM', 'GUY CARPENTER REINMEX LTDA');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600052391', '860005239', 0, 19000, 0, null, null, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'SEGUROS TEQUENDAMA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600052393', '860005239', 0, 19000, 0, null, 11, 1100, 'KR 7 # 26 - 20', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '6677313', null, null, null, 'SEGUROS TEQUENDAMA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600095681', '860009568', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'COMPANIA GRANADINA DE SEG. S.A');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A01891051', '444444074', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'CHANCELOR RE');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('444440592011', '444440592', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1212238949', null, null, 'ST. PAUL REINSURANCE - IRIS LTDA');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444441212831', '444444121', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'COMPAÑIA DE SEGUROS DEL INTERIOR - LATINBROKERS S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444441381', '444444138', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'C.N.A. REINSURANCE.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444441501', '444444150', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'EMPLOYERS REINSURANCE.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444441591', '444444159', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'EVEREST REINSURANCE CO LTD.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444441701', '444444170', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'R+V VERSICHERUNG AG');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444441771', '444444177', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'WHITE MOUNTAIN REINSURANCE COMPANY (FOLKSAMERICA)');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444441951', '444444195', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'SUL AMERICAN BANDEIRANTES');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444441981', '444444198', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'GUILDHALL INSURANCE COMPANY LTD.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444442114821', '444444211', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'HAMBURGUER INTERNATIONAL RUCK - COVER C.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444442131', '444444213', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'HANNOVER RUCKVERSICHERUNGS.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444321', '444444432', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'AMERICAN REINSURANCE COMPANY');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444391', '444444439', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'REASEGURADORA DE LOS ANDES.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444434741', '444444443', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ABEILLE PAIX REASSURANCE - HEATH COL');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444441', '444444444', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ASEGURADORA DE CAUCIONES.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444472831', '444444447', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ASEGURADORA  DE CREDITOS Y GARANTIAS - LATINBROKERS');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444581', '444444458', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'REASEGUROS ALIANZA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444601', '444444460', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'REASEGURADORA PATRIA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444621', '444444462', 0, 19000, 0, null, null, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'REASEGURADORA DEL ISTMO');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444662831', '444444466', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'BANCO DE SEGUROS DEL ESTADO - LATINBROKERS');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444731', '444444473', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'BERISFORD MOCATTA LTD.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444741', '444444474', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'C.E. HEATH LTD');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444791', '444444516', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'MUTUELLE CENTRALE DE REASSURANCE');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444821', '444444482', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'C.A. COVER');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444851', '444444485', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'REAFIANZADORA Y REASEGURADORA DE AMERICA-RASA-');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444881', '444444488', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'PERSEUS REINSURANCE');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444911', '444444491', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'REINSURANCE AUSTRALIA CORPORATION.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444445331', '444444533', 0, 19000, 0, null, null, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, ' 6199382  ', null, null, 'SCOR RE (CONTRATO NUEVO)');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444445411', '444444541', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'AFIANZADORA Y REAFIANZADORA IBEROAMERICANA ARIBESA');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444445451', '444444545', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'SOCIETE COMMERCIALE DE REASSURANCES');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444445471', '444444547', 0, 19000, 0, null, null, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'SOREMA GROUPAMA.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444445811', '444444581', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'SUIZA DE REASEGUROS');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444445831', '444444583', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'THE MERCANTILE AND GENERAL REINSURANCE');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444445851', '444444585', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'TELA VERSICHERUNG');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444445861', '444444586', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'TUTORA CIA. SURAMERICANA DE SEGUROS');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444445871', '444444587', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'WESTER STAR');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444445891', '444444589', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'THE COPENHAGUEN REINSURANCE');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444445911', '444444591', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, ' 305593970', null, null, 'TRANSATLANTIC REINSURANCE');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444445951', '444444595', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'TREWINCK INTERNATIONAL LIMITED.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444446031', '444444603', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'RENASA');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444446201', '444444620', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'UNIONE ITALIANA DI RIASSICURAZIONE');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444446251', '444444625', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'VICTORY INSURANCE COMPANY');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444446261', '444444626', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'GURSA - GRUPO UNIVERSAL DE REASEGUROS');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444446301', '444444630', 0, 19000, 0, null, null, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ZURICH REINSURANCE COMPANY');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444446351', '444444635', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'DELVAG COLOGNE RUCK');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444446401', '444444640', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ANCHORAGE FIRE AND CASUALTY');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444446461', '444444646', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'INTERNATIONAL CASUALTY');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444446481', '444444648', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'PROVIDENT CAPITAL INDEMNITY');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600021853', '860002185', 0, 19000, 0, null, 11, 1100, 'CR 7  32  85 PI 8', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2850072', null, null, 'UNIFIN@INTERRED.NET.CO', 'SEGUROS UNIVERSAL S.A. EN LIQUIDACION');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600024471', '860002447', 0, 19000, 0, null, null, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'COMPANIA DE SEGUROS COLMENA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600024473', '860002447', 0, 19000, 0, null, 11, 1100, 'CL 72  10  07 AP PI 8', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2119111', null, null, null, 'COMPANIA DE SEGUROS COLMENA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600032231', '860003223', 0, 19000, 0, null, 15, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'REASEGURADORA DE COLOMBIA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600032233', '860003223', 0, 19000, 0, null, 15, 1500, 'KR 7 # 71 - 21 TO B PI 15', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '6069305', null, null, null, 'REASEGURADORA DE COLOMBIA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600054391', '860005439', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'LA NACIONAL CIA DE SEGUROS DE VIDA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600346931', '860034693', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'REAL SEGUROS S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600346933', '860034693', 0, 19000, 0, null, 11, 1100, 'CR 7  114  33 PI 16', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '5231400', null, null, 'JULIO.ALBERTO.PEDREROS@CO.ABNAMRO.COM', 'REAL SEGUROS S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600691951', '860069195', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'REASESORES LTDA CORREDORES DE REASEGUROS');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600691953', '860069195', 0, 19000, 0, null, 11, 1100, 'CR 14  86 A  48', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2185611', null, null, 'REACALE@LATINO.NET.CO', 'REASESORES LTDA CORREDORES DE REASEGUROS');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600759261', '860075926', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'REASEGURADORA HEMISFERICA S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8605058001', '860505800', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3134246206', null, 'A.P.CORREDORES INTERNACIONALES DE REASEGUROS.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8605058003', '860505800', 0, 19000, 0, null, 11, 1100, 'TV 3 N  48 A  08', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '7434344', null, '3134246206', 'AP.CORREDORES@INTER.NET.CO', 'A.P.CORREDORES INTERNACIONALES DE REASEGUROS.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8908001521', '890800152', 0, 19000, 0, null, 8, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'SEGUROS ATLAS - EN LIQUIDACION');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8908001523', '890800152', 0, 19000, 0, null, 17, 1700, 'CL 21  23  22', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2866305', null, null, 'SATLAS@TERRA.COM.CO', 'SEGUROS ATLAS - EN LIQUIDACION');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A00000051', '444444441', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, ' CHIYODA FIRE & MARINE INS.CO');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444442531', '444444253', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'AFIANZADORA INSURGENTES.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444442571', '444444257', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'INTERHEMISFERIC REINSURANCE CO.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444442661', '444444266', 0, 19000, 0, null, 41, 206, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'DIE KOLNISCHE RUCKVERSICHERUNG');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444442711', '444444271', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'LATINOAMERICANA DE REASEGUROS -LARSA-');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444442801', '444444280', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'LEGAL AND GENERAL INSURANCE');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444442831', '444444283', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'LATINBROKER S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444442901', '444444290', 0, 19000, 0, null, null, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'XL RE LATIN  AMERICA AG');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444442941', '444444294', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'MAPFRE SERVICIO DE REASEGUROS S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444443031', '444444303', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'MUTUALLE GENERALE FRANCAISE ACCIDENTS');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444443061', '444444306', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'MUNCHENER RUCKVERSICHERUNG GESELLSCHALFT.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444443121', '444444312', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'NATIONALE BORG MAATSCHAPPIJ                           ');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444443141', '444444314', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'NASCO UK HODINGS LTD.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444443161', '444444316', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'N.R.G. ANTILLEAN REINSURANCE -HEATH-');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444443241', '444444324', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'NEW ROTTERDAM INSURANCE COMPANY');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444443551', '444444355', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'NATIONAL VULCAN ENGINNERING GROU');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444443581', '444444358', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'NATION WIDE MUTUAL INSURANCE');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444443701', '444444370', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'KOREAN REINSURANCE COMPANY LIMITED');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444443721', '444444372', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'OCASO REASEGUROS');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444151', '444444415', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Q.B.E.INSURANCE COMPANY LTD.- IRIS LTDA');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444161', '444444416', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ALL STATE INSURANCE COMPANY');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444181', '444444418', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'AMERICANA DE REASEGUROS');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444211', '444444421', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ASSICURAZIONI GENERALI S.P.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444251', '444444425', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ASSURANCES DU CREDIT-NAMUR REASSURANCES');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444281', '444444428', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'REASEGURADORA ALBATROS');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8000678401', '800067840', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'IRIS LTDA CORREDORES DE REASEGUROS');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8000678403', '800067840', 0, 19000, 0, null, 11, 1100, 'AK 9  123  76 OF 202 203 STA BARBARA HOR', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '6378499', null, null, 'IRIS_GERENCIA@SKY.NET.CO', 'IRIS LTDA CORREDORES DE REASEGUROS');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8001392931', '800139293', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3157535039', null, 'JARAMILLO CORREDORES DE REASEGUROS');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8001392933', '800139293', 0, 19000, 0, null, 11, 1100, 'CR 7  145  38 MZ 4 TO 4 AP 302', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '6223390', null, '3157535039', 'JJARAMILLO@JARAMILLORE.COM', 'JARAMILLO CORREDORES DE REASEGUROS');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8001472891', '800147289', 0, 19000, 0, null, null, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'REASEGURADORA NUEVO MUNDO');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8001537901', '800153790', 0, 19000, 0, null, null, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ANDINA DE CORRETAJE DE REASEGUROS LTDA');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8300064531', '830006453', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'MC NEILL - RE');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8300064533', '830006453', 0, 19000, 0, null, 11, 1100, 'CL 125 A  53 A  53', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '6432070', null, null, null, 'MC NEILL - RE');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8300103851', '830010385', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'PROINTER LTDA CORREDORES DE REASEGUROS S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8300103853', '830010385', 0, 19000, 0, null, 11, 1100, 'AK 19  120  00 OF 512', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '6555829', null, null, 'FERNANDO.TELLEZ@ARM-RE.COM', 'PROINTER LTDA CORREDORES DE REASEGUROS S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8600021851', '860002185', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'SEGUROS UNIVERSAL S.A. EN LIQUIDACION');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A00779321', '000000000000', 0, 19000, 0, null, null, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'UNION TEMPORAL TITECO Y/O ECOPETROL S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('4444444444441', '444444444444', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'THE COPENHAGUEN REINSURANCE - HEATH COL');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A04065681', '444444427', 0, 19000, 0, null, null, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'THE LPA GROUP INC.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A00011061', '800216567', 0, 19000, 0, null, 11, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '6369236   ', '3163054404', null, 'CONESA ASOCIADOS CORREDORES DE REASEGUROS');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('A00011063', '800216567', 0, 19000, 0, null, 11, 1100, 'CR 13  90  36 OF 6 04', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '6113101', null, '3163054404', 'JAZMIN.ROMERO@ALSARE.COM', 'CONESA ASOCIADOS CORREDORES DE REASEGUROS');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8903002241', '890300224', 0, 19000, 0, null, 5, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ASEGURADORA DEL VALLE S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('8903002243', '890300224', 0, 19000, 0, null, 5, 5000, 'CL 53  45  112 OF 902', 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '2512081', null, null, null, 'ASEGURADORA DEL VALLE S.A.');

insert into mig_direcciones_conf (MIG_PK, MIG_FK, SPERSON, CAGENTE, CDOMICI, CPOSTAL, CPROVIN, CPOBLAC, TNOMVIA, CTIPDIR, CVIAVP, CLITVP, CBISVP, CORVP, NVIAADCO, CLITCO, CORCO, NPLACACO, COR2CO, CDET1IA, TNUM1IA, CDET2IA, TNUM2IA, CDET3IA, TNUM3IA, LOCALIDAD, TNUMTEL, TNUMFAX, TNUMMOV, TEMAIL, TALIAS)
values ('1111111111111', '111111111111', 0, 19000, 0, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'NATION WIDE MUTUAL INSURANCE - ANCOR LTDA');

prompt Done.
