DELETE CONTADORES_AGENTE WHERE cempres = 24;
--
insert into CONTADORES_AGENTE (CEMPRES, CTIPAGE, CONTADOR, CTIPCONTA)
values (24, 0, 1, 1);

insert into CONTADORES_AGENTE (CEMPRES, CTIPAGE, CONTADOR, CTIPCONTA)
values (24, 1, 1, 1);

insert into CONTADORES_AGENTE (CEMPRES, CTIPAGE, CONTADOR, CTIPCONTA)
values (24, 2, 1, 2);

insert into CONTADORES_AGENTE (CEMPRES, CTIPAGE, CONTADOR, CTIPCONTA)
values (24, 3, 1, 2);

insert into CONTADORES_AGENTE (CEMPRES, CTIPAGE, CONTADOR, CTIPCONTA)
values (24, 4, 1, 4);

insert into CONTADORES_AGENTE (CEMPRES, CTIPAGE, CONTADOR, CTIPCONTA)
values (24, 5, 1, 5);

insert into CONTADORES_AGENTE (CEMPRES, CTIPAGE, CONTADOR, CTIPCONTA)
values (24, 6, 1, 6);
